#! /bin/sh
TOPDIR=`dirname $0`
VERSIONIN=$TOPDIR/hieroglyph/hgversion.h.in.in
VERSION_H=${VERSIONIN//.in.in}.in
UUID=`uuidgen`

echo "Regenerating $VERSION_H"
sed -e "s/%%HIEROGLYPH%%/$UUID/" $VERSIONIN > $VERSION_H
